config/routes.rb
PetDoctors::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "static_pages/contact"

  devise_for :users

  resources :appointments

  resources :customers, :controller => 'profiles', :type => 'Customer'
  resources :doctors, :controller => 'profiles', :type => 'Doctor'
  resources :receptionists, :controller => 'profiles', :type => 'Receptionist'
  resources :profiles

  resources :pets

  root :to => 'appointments#index'

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  validates_presence_of :age, :breed, :customer_id, :dateApp, :petName, :reason, :petType, :weight
  validates_length_of :petName, :maximum => 35
  validates_length_of :breed, :maximum => 35
  attr_accessible :age, :breed, :customer_id, :dateApp, :petName, :reason, :petType, :weight
  belongs_to :customer
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.json

  before_filter :authenticate_user!
  before_filter :get_profile!

  def index
    @pets = @profile.pets

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    @pet = @profile.pets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/new
  # GET /pets/new.json
  def new
    @pet = @profile.pets.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = @profile.pets.find(params[:id])
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = @profile.pets.new(params[:pet])

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render json: @pet, status: :created, location: @pet }
      else
        format.html { render action: "new" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.json
  def update
    @pet = @profile.pets.find(params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet = @profile.pets.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url }
      format.json { head :no_content }
    end
  end

  private
  def get_profile!
    @profile = current_user.profile
  end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form_center> 
  <div class="field">
    <%= f.label "Customer: #{current_user.profile.name}" %><br />
  </div>
  <div class="field">
    <%= f.label "Pet Name: " %><br />
    <%= f.text_field :petName %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
   
    <%=  f.select :petType, [['Dog','dog'],['Cat','cat'],['Bird','bird']] %>
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label "Appointment Date: " %><br />
    <%= f.text_field :dateApp %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason, :rows => 10,:cols => 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/pets/edit.html.erb
<div class="center hero-unit">
<h3>Editing pet</h3>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>
</div>

app/views/pets/index.html.erb
<div class="center hero-unit">
    <h3>Listing pets</h3>

    <table border="1" align="center">
        <tr>
            <th>Customer</th>
            <th>Pet Name</th>
            <th>Type of Pet</th>
            <th>Breed</th>
            <th>Age of Pet</th>
            <th>Weight</th>
            <th>Appointment Date</th>
            <th>Reason</th>
        </tr>

        <% @pets.each do |pet| %>
        <tr>
            <td><%= pet.customer_id %></td>
            <td><%= pet.petName %></td>
            <td><%= pet.petType %></td>
            <td><%= pet.breed %></td>
            <td><%= pet.age %></td>
            <td><%= pet.weight %></td>
            <td><%= pet.dateApp %></td>
            <td><%= pet.reason %></td>
            <td><%= link_to 'Show', pet %></td>
            <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
            <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </table>

    <br />

    <%= link_to 'New Pet', new_pet_path, class: "btn btn-small" %>
</div>

app/views/pets/new.html.erb
<div class="center hero-unit">
<h3>New pet</h3>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>
</div>

app/views/pets/show.html.erb
<div class="center hero-unit">
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @pet.customer.name %>
</p>

<p>
  <b>Petname:</b>
  <%= @pet.petName %>
</p>

<p>
  <b>Type:</b>
  <%= @pet.petType %>
</p>

<p>
  <b>Breed:</b>
  <%= @pet.breed %>
</p>

<p>
  <b>Age:</b>
  <%= @pet.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @pet.weight %>
</p>

<p>
  <b>Dateapp:</b>
  <%= @pet.dateApp %>
</p>

<p>
  <b>Reason:</b>
  <%= @pet.reason %>
</p>


<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>
</div>