config/routes.rb
PetDoctors::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "static_pages/contact"

  devise_for :users

  resources :appointments

  resources :customers, :controller => 'profiles', :type => 'Customer'
  resources :doctors, :controller => 'profiles', :type => 'Doctor'
  resources :receptionists, :controller => 'profiles', :type => 'Receptionist'
  resources :profiles

  resources :pets

  root :to => 'appointments#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :customer_id, :doctor_id, :pet_id, :reminder, :visitDate, :visitReason
  validates :customer_id, :doctor_id, :pet_id, :reminder, :visitReason, presence: true
  belongs_to :customer, :foreign_key => 'customer_id', :class_name => 'Customer'
  belongs_to :doctor, :foreign_key => 'doctor_id', :class_name => 'Doctor'
  
  def doctor_name
      doctor.try(:name)
    end
    
    def doctor_name=(name)
      self.doctor = Doctor.find_or_create_by_name(name) if name.present?
    end
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # GET /appointments
  # GET /appointments.json

  
    def index
      
            # puts current_user.profile.inspect
            
            # @appointments = current_user.profile.appointments
            # @appointments_by_date = @appointments.group_by(&:visitDate)
            
        @appointments= Appointment.all
      #@appointments = @profile.appointments
      
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @appointments }
        end
      end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
    @appointment = current_user.profile.appointments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/new
  # GET /appointments/new.json
  def new
      @appointment = current_user.profile.appointments.build
      @doctors = Doctor.all
   # @appointment = Receptionist.all

 
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @appointment }
    end
  end

  # GET /appointments/1/edit
  def edit
    @appointment = current_user.profile.appointments.find(params[:id])
  end

  # POST /appointments
  # POST /appointments.json
  def create
   @appointment = current_user.profile.appointments.new(params[:appointment])
  # @receptionist = @profile.receptionists.new(params[:receptionist])
    #@appointment = Receptionist.all
      
      respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render json: @appointment, status: :created, location: @appointment }
      else
        format.html { render action: "new" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /appointments/1
  # PUT /appointments/1.json
  def update
    @appointment = current_user.profile.appointments.find(params[:id])

    respond_to do |format|
      if @appointment.update_attributes(params[:appointment])
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment = current_user.profile.appointments.find(params[:id])
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end



end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=f.label "Customer: #{@profile.name}" %><br />
 </div>--> 
  <div class="field">
    <%= f.label :date_of_visit %><br />
    <%= f.text_field :visitDate %>
  </div>
  <div class="field">
    <%= f.label "Pet Name: " %><br />
    <%= f.number_field :pet_id %>
  </div>
  <div class="field">
    <%= f.label :Reminder %><br />
    <%= f.check_box :reminder %>
  </div>
  <div class="field">
    <%= f.label :reason_for_visit %><br />
    <%= f.text_area :visitReason, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label "Doctor: " %><br />
    <%= f.text_field :doctor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<div class="center hero-unit">
<h3>Editing appointment</h3>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>
</div>

app/views/appointments/index.html.erb
<div class="center hero-unit">
<h3>Listing appointments</h3>

<table border="1" align="center">
  <tr>
    <th>Visit Date</th>
    <th>Customer</th>
    <th>Pet</th>
    <th>Reminder</th>
    <th>Visit Reason</th>
    <th>Doctor</th>
  </tr>

<% @appointments.each do |appointment| %>
  <tr>
    <td><%= appointment.visitDate %></td>
    <td><%= appointment.customer_id %></td>
    <td><%= appointment.pet_id %></td>
    <td><%= appointment.reminder %></td>
    <td><%= appointment.visitReason %></td>
    <td><%= appointment.doctor_id %></td>
    <td><%= link_to 'Show', appointment %></td>
    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
    <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
 <div id="articles">
 
 </div>
<br />

<%= link_to 'New Appointment', new_appointment_path, class: "btn btn-small" if can? :new, current_user.profile 
%>
</div>

app/views/appointments/new.html.erb
<div class="center hero-unit">
<h3>New appointment</h3>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>
</div>

app/views/appointments/show.html.erb
<div class="center hero-unit">
<p id="notice"><%= notice %></p>

<p>
  <b>Visitdate:</b>
  <%= @appointment.visitDate %>
</p>

<p>
  <b>Customer:</b>
  <%= @appointment.customer_id %>
</p>

<p>
  <b>Pet:</b>
  <%= @appointment.pet_id %>
</p>

<p>
  <b>Reminder:</b>
  <%= @appointment.reminder %>
</p>

<p>
  <b>Visitreason:</b>
  <%= @appointment.visitReason %>
</p>

<p>
  <b>Doctor:</b>
  <%= @appointment.doctor_id %>
</p>


<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>
</div>