config/routes.rb
PetDoctors::Application.routes.draw do
  get "static_pages/home"

  get "static_pages/help"

  get "static_pages/about"

  get "static_pages/contact"

  devise_for :users

  resources :appointments

  resources :customers, :controller => 'profiles', :type => 'Customer'
  resources :doctors, :controller => 'profiles', :type => 'Doctor'
  resources :receptionists, :controller => 'profiles', :type => 'Receptionist'
  resources :profiles

  resources :pets

  root :to => 'appointments#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
    by Aashish
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "pets Doctor", new_user_session_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", new_user_session_path %></li>
          <li><%= link_to "Help", static_pages_help_path %></li>
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.username %></strong>
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header2.html.erb
<div class="header" >
    <div class="headercontent" >
        <span >| <%= link_to "My Profile", edit_profile_path(current_user.profile)  %> |
            <%= link_to "Appointments", :controller => :appointments, :action => :index %> |
            <%= link_to "Pets", :controller => :pets, :action => :index %> |
            <%#= link_to "Doctors", :doctors, :action => :index if can? :index, current_user.profile %> </span>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pet Doctors</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'jquery.min', 'jquery-ui-1.8.2.custom.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/header' %>
   <%= render 'layouts/header2' if current_user %>

  <%= yield %>

   <%= render 'layouts/footer' %>
  </div>
</body> 
</html>